### ISSUE TITLE
Database migrations and data import/export

### ISSUE THREAD

**Issue by matthewmorek** [JasonEtco/flintcms#69]
I'm not too familiar with MongoDB, though I've enjoed using database migrations and seeding that is available in frameworks, such as Laravel.

I'm wondering how to migrate/import/export database/collections to/from MongoDB, in order to keep the project consistent between environments? Is there some sort of hidden magic, or JSON exporter/importer tool (given that Mongo is a BSON)?

How do you guys recommend approaching this? With SQL it's fairly easy, create a dump and reimport it to another env.

**Comment by JasonEtco** [comment]
@matthewmorek you would typically use [`mongoimport`](https://docs.mongodb.com/manual/reference/program/mongoimport/) or [`mongorestore`](https://docs.mongodb.com/manual/reference/program/mongorestore/) to populate a fresh database.

I'm going to close this because it doesn't really fit into what FlintCMS does; if this is more of a feature request feel free to reopen, but I think its out of the scope of a CMS.

**Comment by matthewmorek** [comment]
I kinda agree, as I found that migrations would be something that would be implemented on the dev side of things for upgrading FlintCMS in the future.

With regards to Import/Export, I think this could be done with plugins. I also learned that MongoDB can also be backedup/restored using `mongodump`, etc, so it's a non-issue at the moment.
